packages:
   - packages/*
onlyBuiltDependencies:
   - esbuild
   - simple-git-hooks
catalog:
   "@eslint/js": 9.21.0
   "@types/node": 22.13.10
   "@vitest/coverage-v8": 3.0.7
   bumpp: 10.0.3
   eslint: 9.21.0
   eslint-plugin-jsonc: 2.19.1
   eslint-plugin-package-json: 0.26.2
   eslint-plugin-yml: 1.17.0
   globals: 16.0.0
   jiti: 2.4.2
   lightningcss: 1.29.2
   lint-staged: 15.4.3
   neostandard: 0.12.1
   simple-git-hooks: 2.11.1
   tsup: 8.4.0
   tsx: 4.19.3
   typescript: 5.8.2
   typescript-eslint: 8.26.0
   vite: 6.2.0
   vitest: 3.0.7
