packages:
   - packages/*

catalog:
   "@types/node": 22.14.1
   typescript: 5.8.3

catalogs:
   build:
      tsup: 8.4.0
   dev:
      tsx: 4.19.3
   lint:
      "@eslint/js": 9.25.1
      eslint: 9.25.1
      eslint-plugin-jsonc: 2.20.0
      eslint-plugin-package-json: 0.29.1
      eslint-plugin-yml: 1.17.0
      globals: 16.0.0
      jiti: 2.4.2
      nano-staged: 0.8.0
      neostandard: 0.12.1
      simple-git-hooks: 2.12.1
      typescript-eslint: 8.26.0
   peer:
      lightningcss: 1.29.3
   testing:
      "@vitest/coverage-v8": 3.1.2
      vitest: 3.1.2
   releasing:
      bumpp: 10.1.0

saveExact: true
blockExoticSubdeps: true
autoInstallPeers: false
minimumReleaseAge: 2880
trustPolicy: no-downgrade
strictPeerDependencies: true
strictDepBuilds: true
dedupePeers: true
shellEmulator: true
color: always

trustPolicyExclude:
   - "undici-types@6.21.0"
   - "synckit@0.10.4"
   - "chokidar@4.0.3"
   - "eslint-import-resolver-typescript@3.10.1"
   - "semver@6.3.1"

allowBuilds:
   esbuild: true
   simple-git-hooks: true
   unrs-resolver: true
