packages:
   - packages/*
onlyBuiltDependencies:
   - esbuild
   - simple-git-hooks
   - unrs-resolver
catalog:
   "@eslint/js": 9.25.1
   "@types/node": 22.14.1
   "@vitest/coverage-v8": 3.1.2
   bumpp: 10.1.0
   eslint: 9.25.1
   eslint-plugin-jsonc: 2.20.0
   eslint-plugin-package-json: 0.29.1
   eslint-plugin-yml: 1.17.0
   globals: 16.0.0
   jiti: 2.4.2
   lightningcss: 1.29.3
   nano-staged: 0.8.0
   neostandard: 0.12.1
   simple-git-hooks: 2.12.1
   tsup: 8.4.0
   tsx: 4.19.3
   typescript: 5.8.3
   typescript-eslint: 8.26.0
   vite: 6.3.2
   vitest: 3.1.2
