name: Release

permissions:
   id-token: write
   contents: write

on:
   push:
      tags:
         - "*@*"

jobs:
   release:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
           with:
              fetch-depth: 0

         - name: Validate tag format
           run: |
              if [[ ! $GITHUB_REF =~ ^refs/tags/[a-zA-Z0-9-]+@[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                echo "Invalid tag format. Expected 'name@x.y.z'."
                exit 1
              fi

         - uses: pnpm/action-setup@v4
         - uses: actions/setup-node@v4
           with:
              node-version: lts/*
              registry-url: https://registry.npmjs.org/

         - run: pnpx changelogithub
           env:
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

         - run: pnpm install
         - run: pnpm publish -r --access public --no-git-checks
           env:
              NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
              NPM_CONFIG_PROVENANCE: true
